name: trivy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    permissions:
      contents: read
      security-events: write
      actions: read
    name: Build and Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh

      # Build main Dockerfile image 
      - name: Build main image
        run: |
          docker build -f Dockerfile -t docker.io/my-organization/my-app:${{ github.sha }} .

      # Scan main image with Trivy (vulnerabilities only)
      - name: Trivy scan SARIF (main)
        uses: aquasecurity/trivy-action@v0.5.0  # <-- Use a stable version, v0.5.0
        with:
          image-ref: 'docker.io/my-organization/my-app:${{ github.sha }}'
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH,MEDIUM,LOW'

      # Upload SARIF to GitHub Security tab
      - name: Upload SARIF (main)
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'
          category: trivy-main

      # Build Dockerfile.val1 (vulnerable image)
      - name: Build vulnerable image
        run: |
          docker build -f Dockerfile.val1 -t docker.io/my-organization/my-val1-app:${{ github.sha }} .

      # Scan vulnerable image with Trivy (vulnerabilities only)
      - name: Trivy scan SARIF (vulnerable)
        uses: aquasecurity/trivy-action@v0.5.0  # <-- Use the stable version v0.5.0
        with:
          image-ref: 'docker.io/my-organization/my-val1-app:${{ github.sha }}'
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-val1-results.sarif'
          severity: 'CRITICAL,HIGH,MEDIUM,LOW'

      # Upload SARIF to GitHub Security tab
      - name: Upload SARIF (vulnerable)
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-val1-results.sarif'
          category: trivy-vulnerable
